version: '3.6'

networks:
    gearman-topology: {}

services:
  memcached-1:
    container_name: memcached-1
    image: memcached-pod-experiment
    entrypoint: memcached -p 11211 -m 64 -l 0.0.0.0 -x memcached-2 -X 11212:11213  -u root -vvv
    networks:
      - gearman-topology
    restart:
      on-failure

  memcached-2:
    container_name: memcached-2
    image: memcached-pod-experiment
    entrypoint: memcached -p 11211 -m 64 -l 0.0.0.0 -x memcached-1 -X 11213:11212 -u root -vvv
    networks:
      - gearman-topology
    restart:
      on-failure
    
  gearman-server:
    container_name: gearman-server
    image: gearman-pod-experiment
    entrypoint: gearmand --log-file=stderr --threads=1 #gearmand --log-file=stderr --verbose=DEBUG --threads=1 --coredump
    networks:
      - gearman-topology
    restart:
      on-failure

  gearman-worker:
    container_name: gearman-worker
    image: gearman-pod-experiment
    entrypoint: /usr/bin/dumb-init -- ./entrypoint-worker.sh
    networks:
      - gearman-topology
    restart:
      always 
      
  gearman-client:
    container_name: gearman-client
    image: gearman-pod-experiment
    entrypoint: sleep 5800000
    networks:
      - gearman-topology
    restart:
      on-failure
